apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  replicas: 1
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
      - name: vprodb
        image: dheenathayalanb/vprofiledb:latest
        volumeMounts:
          - name:  vprodb-data
            mountPath: /var/lib/mysql
        ports:
        - name: vprodb-port
          containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: db-pass
      nodeSelector:
        zone: us-west-2a
      volumes:
      - name: vprodb-data
        awsElasticBlockStore:
          volumeID: vol-00cf797eb1e951707
          fsType: ext4
      initContainers:
      - name: init-db
        image: busybox:latest
        volumeMounts:
          - name: vprodb-data
            mountPath: /var/lib/mysql
        args: ["rm", "-rf", "/var/lib/mysql/lost+found"]
